### ISSUE TITLE
[bug]: Error starting web interface on M1 Mac

### ISSUE THREAD

**Issue by waterydan** [invoke-ai/InvokeAI#4822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.2.0

### What happened?

I just installed invoke 3.2 on Macbook Pro M1 Max. The installation finished without any issues, but when I tried to launch the web interface (option 1), it exists with this error. Any ideas what might be causing this?

Generate images with a browser-based interface
Traceback (most recent call last):
  File "/Users/dwai/invokeai/.venv/bin/invokeai-web", line 5, in <module>
    from invokeai.app.api_app import invoke_api
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/api_app.py", line 33, in <module>
    from .api.dependencies import ApiDependencies
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/api/dependencies.py", line 12, in <module>
    from invokeai.app.services.images import ImageService, ImageServiceDependencies
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/services/images.py", line 32, in <module>
    from invokeai.app.util.metadata import get_metadata_graph_from_raw_session
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/util/metadata.py", line 6, in <module>
    from invokeai.app.services.graph import Edge
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/services/graph.py", line 14, in <module>
    from ..invocations import *  # noqa: F401 F403
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/invocations/latent.py", line 811, in <module>
    class ImageToLatentsInvocation(BaseInvocation):
  File "/Users/dwai/invokeai/.venv/lib/python3.9/site-packages/invokeai/app/invocations/latent.py", line 897, in ImageToLatentsInvocation
    def _(vae: AutoencoderTiny, image_tensor: torch.FloatTensor) -> torch.FloatTensor:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 909, in register
    return self.dispatcher.register(cls, func=method)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 851, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`: <staticmethod object at 0x29cb73880>. Use either `@register(some_class)` or plain `@register` on an annotated function.

### Additional context

Python 3.11.5 installed.

**Comment by smaclell** [comment]
I had this same error on an M2 Max while using Python 3.9. I upgraded to Python 3.11.6, reinstalled and was able to run the web interface.

Could you try running `python --version` to confirm it is using Python 3.11.5? The stacktrace looks like it might be trying to use python 3.9 based on this directory:
 "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/

**Comment by psychedelicious** [comment]
Thanks @smaclell

We will be dropping support for python 3.9 very soon (see #4728) but that isn't implemented yet, so I wonder if this is a macos-specific issue. FWIW, my m1 mac has python 3.10.12 and I do not have this issue.

**Comment by waterydan** [comment]
I completely removed python3 and reinstalled it using pyenv... it's still not working.
Running `python --version` in terminal shows Python 3.12.0 is installed

**Comment by psychedelicious** [comment]
@waterydan Can you please use the launcher, select the dev console option, and then run `python --version` inside that? 

This appears to be a bug that was fixed in python 3.9.8:
- https://stackoverflow.com/questions/62696796/singledispatchmethod-and-class-method-decorators-in-python-3-8
- https://bugs.python.org/issue39679

Notably, my M1 mac with the macOS Sonoma 14.0 (23A344) has with python 3.9.6 installed. So I wonder if the version inside your venv is not updated

**Comment by waterydan** [comment]
You got it! It is indeed showing 3.9.6 in the dev console. Sorry I'm a noob in Python. How can I change the version to latest?

**Comment by psychedelicious** [comment]
@waterydan I'm afraid I don't know. Somehow, my venvs magically use the version of python I installed via homebrew.

@keturn , can you point us in the right direction to change the python version used by the venv? Would just recreating the venv do it?

**Comment by keturn** [comment]
yes, a venv uses the Python that was used to create it.

**Comment by waterydan** [comment]
Sorry i'm still not sure how to do that... there's already a .venv folder. Do I delete that and create a new one using python?

**Comment by psychedelicious** [comment]
thanks @keturn 

@waterydan The best way is to just reinstall the app. Delete the `.venv` folder and run the installer again.

**Comment by waterydan** [comment]
Finally got it working after reinstalling! Thanks @psychedelicious !

**Comment by psychedelicious** [comment]
@waterydan No worries. Whew, glad you are up and running! Hope you enjoy the app
