### ISSUE TITLE
mach-o file is an incompatible architecture (have (x86_64), need (arm64e))

### ISSUE THREAD

**Issue by woutervanwijk** [invoke-ai/InvokeAI#730]
**Describe your environment**
- Mac M1 / Macos
- Python: miniconda
- main
- commit a1739a73b48bfe98b6abcb67f5a0197a9ad270e0 (HEAD -> main, origin/main, origin/HEAD)

**Describe the bug**
I followed all the instructions, but got this error:

```
Traceback (most recent call last):
  File "/Users/wouter/code/stable-diffusion/scripts/preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/Users/wouter/miniconda3/envs/ldm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 992, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/wouter/miniconda3/envs/ldm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1004, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback):
dlopen(/Users/wouter/miniconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so, 0x0002): tried: '/Users/wouter/miniconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```
And if I do 
`uname -m`
I get arm64. Don't know what I did wrong

**Comment by jroxendal** [comment]
did you do conda create as in the docs?
`PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml`
the conda subdir env should fix the incompatible architecture issue, at least it did for me!

**Comment by woutervanwijk** [comment]
Thanks, yes, I used it. And tried again and again. Weird

**Comment by woutervanwijk** [comment]
Ok, I solved the problem after a lot of trial & error. 

Changed to miniforge, back to miniconda, etc. No avail.

The Problem: my brew was still running on Rosetta. Fixed that by uninstalling, cleaning and reinstalling. So everything seemed to run fine. Except this problem still kept cropping up

Until I discovered that pip is quite agressive in caching. So it caches the build even if the architecture changed. Solution: pip cache purge. Or remove the whole cache directory which you find with pip cache info
