### ISSUE TITLE
[bug]: Starring Not Working Well on v6 RC 5 Infinite Scroll

### ISSUE THREAD

**Issue by ladle3000** [invoke-ai/InvokeAI#8242]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

a4000

### GPU VRAM

16

### Version number

6 rc 5

### Browser

Firefox

### Python dependencies

V6 RC 5 - I can''t get the stars to consistently register. After page reloads they are sometimes there on ones I clicked like 6 times.  Other times if I resize the images grid then they magically show up

### What happened

tried to star stuff

### What you expected to happen

stuff to get starred

### How to reproduce the problem

Try to star stuff consistently on firefox on RC 5

**Comment by hipsterusername** [comment]
Does this hold true for you in 6.0 release?

**Comment by psychedelicious** [comment]
This is fixed in v6.0.0

**Comment by ladle3000** [comment]
It's the same 6.0.0. Very frustrating. Also downloading boards throws an error about missing images, so I can't download boards.

**Comment by ladle3000** [comment]
> This is fixed in v6.0.0

Not on my Linux install.

**Comment by ladle3000** [comment]
@psychedelicious @hipsterusername just updated to 6.0.2 and the issue persists. I use firefox - if that is of use to find this bug. I can't organize anything. It works like one time out of 10 now. Worked flawless on 5.x on firefox.  Please reopen or advise

**Comment by ladle3000** [comment]
And here is the seemingly related issue of not being able to download certain boards. 

<img width="558" height="118" alt="Image" src="https://github.com/user-attachments/assets/864659bd-9599-485e-bb09-1794c363f13c" />

**Comment by psychedelicious** [comment]
Please take a video recording showing the problem with starring to help me understand it. I fixed the issue you described but maybe there are two different issues. 

Please make a separate issue for downloading boards.

**Comment by ladle3000** [comment]
I'll try to do it tomorrow.

Thank you,
-scott

Sent with Proton encrypted email service.

-------- Original Message --------

**Comment by hipsterusername** [comment]
FWIW - I have been unable to replicate any starring issues, so getting some more 'local' context will help

**Comment by ladle3000** [comment]
@psychedelicious @hipsterusername 

Is there a command from Linux cli to reindex the database with what images actually still exist in the gallery.  I have a feeling this and the inability to download some boards point to an inconsistency between what the DB and the gallery actually contain.  Speculating, since I periodically delete images directly from an sftp connection to the images folder. 

I'd like to try some DB maintenance first if possible before going through and making a video. 

My train of thought is that if the DB think there should be images there that aren't there when packaging up a board, it throws an error. Likewise, when trying to start, perhaps visually a thumbnail is where the identifier for a previous thumbnail that has since been deleted server side is supposed to exist. Hence the intermittent working of stars and boards

**Comment by ladle3000** [comment]
@psychedelicious @hipsterusername I did a video anyway. But still interested in a sync tool per last comment (please read).  But here are 5 sample images I put in assets. Behavior is the same in assets and images, this was just easier to upload and show on new boards. Video shows me over an over trying to star. Screenshot shows that some were in fact starred after revisiting. It seems to be hit or miss what actually gets starred. Or it works on every single click like it should, but the UI is not showing the star filling in real time (or going hollow).  Screenshot shows 4 of 5 got starred in the end.  But not being able to see and confirm in real-time is unworkable. **And yes, I'm clicking each time I hover a star, multiple times in some cases. Just forgot to record click input.**

https://github.com/user-attachments/assets/78c1c2b7-0813-42e3-a1b9-0ad4d3b070db

<img width="418" height="836" alt="Image" src="https://github.com/user-attachments/assets/9c20beea-1ad6-4a65-9b7a-b8b82fbe829a" />

**Comment by psychedelicious** [comment]
Not sure why it isn't working for you. I cannot reproduce it, tried every combination of `starred first` and `newest first/oldest first`, which are the gallery sort settings. Do you have errors in the launcher logs, browser JS console or browser network logs? When you star an image, do you see a network request?

Regarding database stuff: If you delete an image file, the only effect we expect is that we cannot show the image to you. It doens't affect starring an image. There are no tools to sync the database with filesystem; you could write a python script to do that for you if needed. We suggest deleting images via the application to prevent inconsistencies like this.

**Comment by ladle3000** [comment]
> Not sure why it isn't working for you. I cannot reproduce it, tried every combination of `starred first` and `newest first/oldest first`, which are the gallery sort settings. Do you have errors in the launcher logs, browser JS console or browser network logs? When you star an image, do you see a network request?
> 
> Regarding database stuff: If you delete an image file, the only effect we expect is that we cannot show the image to you. It doens't affect starring an image. There are no tools to sync the database with filesystem; you could write a python script to do that for you if needed. We suggest deleting images via the application to prevent inconsistencies like this.

It's on the 6.0 side of things. NEVER had this issue once on 5.x

But I can check dev console tomorrow for you to see if there is any clue.  I'll try chrome also, since I've only ever used invoke with Firefox.

**Comment by psychedelicious** [comment]
I understand it's a new issue, we'll fix it. Just need more information or a way to reproduce it.
